name: Build and Publish TTSInstaller

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '6.0.x'

      - name: Install WiX Toolset
        run: |
          dotnet tool install --global wix

      - name: Restore Dependencies
        run: dotnet restore TTSInstaller.sln

      - name: Build Project
        run: |
          dotnet build TTSInstaller.sln -c Release
          dotnet publish TTSInstaller.csproj -c Release -r win-x64 --self-contained true /p:PublishSingleFile=true

      - name: Download Model Files
        run: |
          # Create the model directory structure
          mkdir -p models\vits-piper-en_US-amy-low\espeak-ng-data
          
          # Download the Piper model files
          $ProgressPreference = 'SilentlyContinue'
          Invoke-WebRequest -Uri "https://huggingface.co/rhasspy/piper-voices/resolve/main/en/en_US/amy/low/en_US-amy-low.onnx" -OutFile "models\vits-piper-en_US-amy-low\en_US-amy-low.onnx"
          Invoke-WebRequest -Uri "https://huggingface.co/rhasspy/piper-voices/resolve/main/en/en_US/amy/low/tokens.txt" -OutFile "models\vits-piper-en_US-amy-low\tokens.txt"
          
          # Download espeak-ng-data files
          Invoke-WebRequest -Uri "https://github.com/espeak-ng/espeak-ng/raw/master/espeak-ng-data/phondata" -OutFile "models\vits-piper-en_US-amy-low\espeak-ng-data\phondata"
          Invoke-WebRequest -Uri "https://github.com/espeak-ng/espeak-ng/raw/master/espeak-ng-data/phondata-manifest" -OutFile "models\vits-piper-en_US-amy-low\espeak-ng-data\phondata-manifest"
          Invoke-WebRequest -Uri "https://github.com/espeak-ng/espeak-ng/raw/master/espeak-ng-data/phonindex" -OutFile "models\vits-piper-en_US-amy-low\espeak-ng-data\phonindex"
          Invoke-WebRequest -Uri "https://github.com/espeak-ng/espeak-ng/raw/master/espeak-ng-data/phontab" -OutFile "models\vits-piper-en_US-amy-low\espeak-ng-data\phontab"
          Invoke-WebRequest -Uri "https://github.com/espeak-ng/espeak-ng/raw/master/espeak-ng-data/intonations" -OutFile "models\vits-piper-en_US-amy-low\espeak-ng-data\intonations"
          Invoke-WebRequest -Uri "https://github.com/espeak-ng/espeak-ng/raw/master/espeak-ng-data/en_dict" -OutFile "models\vits-piper-en_US-amy-low\espeak-ng-data\en_dict"
          
      - name: Build WiX Installer
        run: dotnet build TTSInstaller.wixproj -c Release -p:Platform=x64

      - name: Upload Build Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: TTSInstaller
          path: |
            ./bin/Release/net6.0-windows/win-x64/publish/TTSInstaller.exe
            ./bin/Release/net6.0-windows/win-x64/publish/OpenSpeechTTS.dll
            ./bin/Release/TTSInstaller.msi

  sign:
    runs-on: windows-latest
    needs: build
    if: always()

    steps:
      - name: Notify Signing Required
        run: |
          echo "The build artifacts are ready but must be signed locally."
          echo "Download them from the artifacts tab and sign the EXE, DLL, and MSI locally."

      - name: Provide Signing Instructions
        run: |
          echo "Use the following commands to sign the artifacts locally:"
          echo "signtool sign /fd SHA256 /a /tr http://timestamp.digicert.com /td SHA256 <path-to-TTSInstaller.exe>"
          echo "signtool sign /fd SHA256 /a /tr http://timestamp.digicert.com /td SHA256 <path-to-OpenSpeechTTS.dll>"
          echo "signtool sign /fd SHA256 /a /tr http://timestamp.digicert.com /td SHA256 <path-to-TTSInstaller.msi>"
